version: '3.8'

services:
  web:
    build: .
    ports:
      - "8099:8099"
    environment:
      API_HOST: "0.0.0.0"
      API_PORT: "8099"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"